package dev.gear.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "basket")
public class Basket {
    @DynamoDBHashKey(attributeName = "customer_id")
    String customer_id;
    @DynamoDBAttribute
    ArrayList<Product> product_list;
    @DynamoDBAttribute
    @Builder.Default // Specify default value for total_price
    BigDecimal total_price = BigDecimal.ZERO;
    public Product addProduct(Product product) {
        if (product_list == null) {
            product_list = new ArrayList<>();
        }
        product_list.add(product);
        return product;
    }
    public Product multiplyTotalPrice(Product product){
        BigDecimal newTotalPrice = total_price.multiply(product.getProduct_price());
        return product;
    }


}
