package dev.gear.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.ArrayList;

@NoArgsConstructor
@Builder
@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "order")
public class Order {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "orderId")
    private String orderId;
    @DynamoDBRangeKey(attributeName = "customerId")
    private String customerId;
    @DynamoDBAttribute
    ArrayList<Product> product;
    @DynamoDBAttribute
    private String paymentMethod;
    @DynamoDBAttribute
    private String deliveryLocation;
    @DynamoDBAttribute
    private String orderStatus;
    @DynamoDBAttribute
    private String createdTimestamp;
    @DynamoDBAttribute
    private String updatedTimestamp;
    @DynamoDBAttribute
    private BigDecimal orderTotalPrice;
}
